### ISSUE TITLE
Migrate SCREW to an organisation space and rename from Epigenomics_CWL to Epigenomics-SCREW

### ISSUE THREAD

**Issue by oneillkza** [NCBI-Hackathons/Epigenomics_CWL#26]
Having SCREW inside the NCBI-Hackathons space has been raising some issues. Although we have permission to rename it, we don't have the ability to grant permissions to third-party tools (e.g. draw.io).

I'd like to create an organisation account (it would be Epigenomic-SCREW), and transfer the codebase there.

@bdecato @neksa @DCGenomics -- are you all OK with this?

**Comment by DCGenomics** [comment]
Is there some reason ncbi-hackathons couldn't give you permission to do the
former?

On Mar 24, 2017 7:15 PM, "oneillkza" <notifications@github.com> wrote:

Having SCREW inside the NCBI-Hackathons space has been raising some issues.
Although we have permission to rename it, we don't have the ability to
grant permissions to third-party tools (e.g. draw.io).

I'd like to create an organisation account (it would be Epigenomic-SCREW),
and transfer the codebase there.

@bdecato <https://github.com/bdecato> @neksa <https://github.com/neksa>
@DCGenomics <https://github.com/DCGenomics> -- are you all OK with this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NCBI-Hackathons/Epigenomics_CWL/issues/26>, or mute the
thread

**Comment by neksa** [comment]
Yes from me. I also think we need a space outside the hackathons and create a fork there.
I used NCBI-hackathons as organization name at quay but we probably need something more specific? Shall I rename it to Epigenomics-SCREW as well?

What do you suggest regarding Paul's workflow? I should probably separate screw and sidearm completely.
Alex

**Comment by oneillkza** [comment]
@DCGenomics , I'm pretty sure you could grant us permission each time we need it, but it would definitely be easier if we could do it ourselves. I also think it would be great to grow the project out of the hackathon space so it can stand on its own. 

@neksa suggested forking it rather than moving, which I think would be a good solution. I think moving would completely pull up roots and leave no trace, and I'd rather there be a record within NCBI-hackathons, which a fork would allow.

@neksa, yes, I think it would be good to separate Screw and Sidearm; what we could do initially would be to leave the existing image under NCBI-hackathons on quay (until Paul has decided what to do with that), and create an Epigenomics-SCREW organisation moving forward to house the screw image.

**Comment by bdecato** [comment]
+1 to the current title: migrating SCREW to an organization space and renaming it to Epigenomics-SCREW.

One other thought is to modify the README.md files in each of the repositories to link to each other: including a History section in the new repo that explains that the project grew out of a hackathon, and a Future Work section in the old repo that links to the organization.

**Comment by oneillkza** [comment]
Done! See https://github.com/Epigenomics-SCREW/SCREW

I've also invited everyone to the organisation. Once you're in and we have permissions set up, I think we can close this issue.

**Comment by oneillkza** [comment]
And yes, definitely +1 to the history section.

**Comment by DCGenomics** [comment]
Still not quite sure I see the necessity, as I could just make you guys
admin on the repo, but you seem pretty set on this, and therefore I would
request the following.

Go with the forking plan for the new org, and then put a redirect link (to
the most current work on the project) at the top of the old readme, so
people can find the new work quickly.

Cheers!

Ben
